# Example: Kubernetes deployment with MINIMUM UTILIZATION REQUIREMENTS enforced
# This configuration ensures your nodes meet the specific thresholds:
# - CPU 95th percentile > 20%
# - Network utilization > 20 Mbps  
# - Memory utilization > 20% (for selected nodes)

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goburn-minimum-requirements
  namespace: default
  labels:
    app: goburn
    purpose: minimum-utilization-enforcement
spec:
  selector:
    matchLabels:
      app: goburn
  template:
    metadata:
      labels:
        app: goburn
    spec:
      serviceAccountName: goburn
      hostNetwork: true
      hostPID: true
      containers:
      - name: goburn
        image: pedromol/goburn:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        # === MINIMUM REQUIREMENTS (ENFORCED) ===
        - name: MIN_CPU_UTILIZATION
          value: "20"        # CPU 95th percentile MUST be > 20%
        - name: MIN_MEMORY_UTILIZATION  
          value: "20"        # Memory utilization MUST be > 20%
        - name: MIN_NETWORK_UTILIZATION_MBPS
          value: "20"        # Network traffic MUST be > 20 Mbps
        
        # === TARGET OPTIMIZATION LEVELS ===
        - name: TARGET_CPU_UTILIZATION
          value: "80"        # Optimize towards 80% CPU (after minimums met)
        - name: TARGET_MEMORY_UTILIZATION
          value: "80"        # Optimize towards 80% memory (after minimums met)
        
        # === CONTROL SETTINGS ===
        - name: MONITOR_INTERVAL_SECONDS
          value: "30"        # Check utilization every 30 seconds
        - name: SCALE_UP_DELAY_SECONDS
          value: "60"        # Wait 1 minute before scaling up
        - name: SCALE_DOWN_DELAY_SECONDS
          value: "120"       # Wait 2 minutes before scaling down
        
        # === SAFETY LIMITS ===
        - name: MAX_MEMORY_MB
          value: "2048"      # Never allocate more than 2GB
        
        # === NODE-SPECIFIC CONFIGURATION ===
        - name: ENABLE_MEMORY_UTILIZATION
          value: "true"      # Set to "false" to disable memory enforcement on specific nodes
        - name: NETWORK_INTERFACE
          value: "eth0"      # Network interface to monitor/generate traffic
        
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "4Gi"    # Allow up to 4GB for enforcement
            cpu: "2000m"     # Allow up to 2 CPU cores
        
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      
      # Run on all nodes to enforce minimum requirements cluster-wide
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      
      nodeSelector:
        kubernetes.io/os: linux
      
      # High priority to ensure minimum requirements are always met
      priorityClassName: system-node-critical

---
# ConfigMap with different profiles for different node types
apiVersion: v1
kind: ConfigMap
metadata:
  name: goburn-profiles
  namespace: default
data:
  # Profile for production nodes - conservative enforcement
  production.env: |
    MIN_CPU_UTILIZATION=20
    MIN_MEMORY_UTILIZATION=20
    MIN_NETWORK_UTILIZATION_MBPS=20
    TARGET_CPU_UTILIZATION=70
    TARGET_MEMORY_UTILIZATION=75
    SCALE_DOWN_DELAY_SECONDS=300
    ENABLE_MEMORY_UTILIZATION=true
  
  # Profile for development nodes - aggressive enforcement
  development.env: |
    MIN_CPU_UTILIZATION=25
    MIN_MEMORY_UTILIZATION=25
    MIN_NETWORK_UTILIZATION_MBPS=30
    TARGET_CPU_UTILIZATION=90
    TARGET_MEMORY_UTILIZATION=85
    SCALE_UP_DELAY_SECONDS=30
    ENABLE_MEMORY_UTILIZATION=true
  
  # Profile for memory-sensitive nodes - CPU and network only
  memory-sensitive.env: |
    MIN_CPU_UTILIZATION=20
    MIN_MEMORY_UTILIZATION=0
    MIN_NETWORK_UTILIZATION_MBPS=20
    TARGET_CPU_UTILIZATION=80
    TARGET_MEMORY_UTILIZATION=50
    ENABLE_MEMORY_UTILIZATION=false
